CREATE SEQUENCE seq_admin
    START WITH 1 INCREMENT BY 1
    MAXVALUE 9999 MINVALUE 1;

CREATE SEQUENCE seq_candidat
    START WITH 1 INCREMENT BY 1
    MAXVALUE 9999 MINVALUE 1;

CREATE SEQUENCE seq_personnel
    START WITH 1 INCREMENT BY 1
    MAXVALUE 9999 MINVALUE 1;

